<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Icon.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		
		<!-- Version Information -->
		<Version>4.5.0</Version>
		<AssemblyVersion>4.5.0.0</AssemblyVersion>
		<FileVersion>4.5.0.0</FileVersion>
		<InformationalVersion>4.5.0</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Icon.ico">
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Versions\*.json" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MirrorsEdgeTweaks.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Eliot.UELib" Version="1.13.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
		<PackageReference Include="NativeSharpLzo" Version="0.3.5" />
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
	</ItemGroup>

</Project>

